on: [push]

name: build

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
            target: aarch64-unknown-linux-gnu

      - name: Install aarch64 gcc
        run: sudo apt install gcc-aarch64-linux-gnu

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=aarch64-unknown-linux-gnu
      - uses: actions/upload-artifact@v2
        with:
          name: aarch64-unknown-linux-gnu-release
          path: target/release/unftp
